AdvertisementApp.UI/Controllers/AdvertisementController.cs
using AdvertisementApp.Business.Interfaces;
using AdvertisementApp.Common.Enums;
using AdvertisementApp.Dtos;
using AdvertisementApp.UI.Base;
using AdvertisementApp.UI.Extensions;
using AdvertisementApp.UI.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AdvertisementApp.UI.Controllers
{
    public class AdvertisementController : BaseController
    {
        private readonly IAppUserService _appUserService;
        private readonly IAdvertisementAppUserService _advertisementAppUserService;
        private readonly IMapper _mapper;

        public AdvertisementController(IAppUserService appUserService, IAdvertisementAppUserService advertisementAppUserService, IMapper mapper) : base(appUserService, mapper)
        {
            _appUserService = appUserService;
            _advertisementAppUserService = advertisementAppUserService;
            _mapper = mapper;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> List(AdvertisementAppUserStatusType type = AdvertisementAppUserStatusType.Basvurdu)
        {
            var advertisements = await _advertisementAppUserService.GetList(type);
            return View(advertisements);
        }

        #region Hocanın Yaptığı Yöntem
        /*
         [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ApprovedList()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Mulakat);
            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RejectedList()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Olumsuz);
            return View(list);
        }
         */
        #endregion


        [Authorize(Roles = "Member")]
        public IActionResult Send(int advertisementId)
        {
            var userId = this.UserGender();

            MilitaryStatusSelectList();

            return View(new AdvertisementAppUserCreateModel
            {
                AdvertisementId = advertisementId,
                AppUserId = userId
            });
        }

        [Authorize(Roles = "Member")]
        [HttpPost]
        public async Task<IActionResult> Send(AdvertisementAppUserCreateModel model)
        {
            var createdAdvertisementAppUser = _mapper.Map<AdvertisementAppUserCreateDto>(model);

            if (model.CvFile != null)
            {
                Utils.File file = new Utils.File();
                file.FileUpload(model.CvFile, fileLocation: "cvFiles", out string validation, out string filePath);
                if (validation == null)
                    createdAdvertisementAppUser.CvPath = filePath;
                else
                    ModelState.AddModelError("", validation);
            }

            var response = await _advertisementAppUserService.CreateAsync(createdAdvertisementAppUser);

            if (response.ResponseType == Common.ResponseType.ValidationError)
            {
                MilitaryStatusSelectList();
                this.UserGender();
            }

            return this.ResponseRedirectAction(response: response, model: model, controllerName: "Home", actionName: "HumanResource");
            // Farklı yönlendirmeler için

            #region Uzun Hali
            //if (response.ResponseType == Common.ResponseType.ValidationError)
            //{
            //    foreach (var error in response.ValidationErrors)
            //    {
            //        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            //    }

            //    return View(model);
            //}
            //else
            //{
            //    return RedirectToAction("HumanResource", "Home");
            //}
            #endregion
        }

        public int UserGender()
        {
            #region Yeni yöntemler
            // int userID = this.UserKey();
            // string userName = this.ClaimType(type: "UserName");
            #endregion

            #region Uzun Yöntem
            // int userId = Convert.ToInt32(this.UserType(type: ClaimTypes.NameIdentifier));
            // var userResponse = await _appUserService.GetByIdAsync<AppUserListDto>(userId);
            // 
            // ViewBag.GenderId = userResponse.Data.GenderId;
            // return userId;
            #endregion

            ViewBag.GenderId = UserInfo.GenderId;
            return Id;
        }

        public void MilitaryStatusSelectList()
        {
            var items = Enum.GetValues(typeof(MilitaryStatusType));
            var list = new List<MilitaryStatusListDto>();

            foreach (int item in items)
            {
                list.Add(new()
                {
                    Id = item,
                    Definition = Enum.GetName(typeof(MilitaryStatusType), item)
                });
            }

            // ViewBag.MilitaryStatus = new SelectList(list, "Id", "Definition");
            ViewBag.MilitaryStatus = SelectListExtensions.SelectListModel(list, "Id", "Definition");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SetStatus(int advertisementAppUserId, AdvertisementAppUserStatusType type)
        {
            await _advertisementAppUserService.SetStatusAsync(advertisementAppUserId, type);
            return RedirectToAction(nameof(List));
        }
    }
}

AdvertisementApp.UI/Controllers/ApplicationController.cs
using AdvertisementApp.Business.Interfaces;
using AdvertisementApp.Dtos;
using AdvertisementApp.UI.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AdvertisementApp.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ApplicationController : Controller
    {
        private readonly IAdvertisementService _advertisementService;

        public ApplicationController(IAdvertisementService advertisementService)
        {
            _advertisementService = advertisementService;
        }

        public async Task<IActionResult> List()
        {
            var response = await _advertisementService.GetAllAsync();
            return this.ResponseView(response);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AdvertisementCreateDto dto)
        {
            var response = await _advertisementService.CreateAsync(dto);
            return this.ResponseRedirectAction(response, nameof(List));
        }

        public async Task<IActionResult> Update(int id)
        {
            var response = await _advertisementService.GetByIdAsync<AdvertisementUpdateDto>(id);
            return this.ResponseView(response);
        }

        [HttpPost]
        public async Task<IActionResult> Update(AdvertisementUpdateDto dto)
        {
            var response = await _advertisementService.UpdateAsync(dto);
            return this.ResponseRedirectAction(response, nameof(List));
        }

        public async Task<IActionResult> Remove(int id)
        {
            var response = await _advertisementService.RemoveAsync(id);
            return this.ResponseRedirectAction(response, nameof(List));
        }
    }
}

AdvertisementApp.UI/Views/Shared/_Layout.cshtml
@{
    string controller = this.ViewContext.RouteData.Values["controller"].ToString();
    string action = this.ViewContext.RouteData.Values["action"].ToString();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Reklam Ajansı</title>
    <link rel="icon" type="image/x-icon" href="~/themes/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/themes/css/styles.css" rel="stylesheet" />
    @RenderSection("css", required: false)
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark @(User.Identity.IsAuthenticated && User.IsInRole("Admin") ? "bg-danger" : "navbar-custom") fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="@(controller=="Home" && action=="Index" ? "#page-top" : "/Home/Index")">Bilge Ajans</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    @{
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="HumanResource">İnsan Kaynakları</a></li>
                        if (User.IsInRole("Admin")) @* Kullanıcının Rolü Admin İçeriyor Mu ?  *@
                        {
                            <li class="nav-item"><a class="nav-link" asp-controller="Advertisement" asp-action="List">Başvurular</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Application" asp-action="List">İş İlanları</a></li>
                        }

                        if (!User.Identity.IsAuthenticated) @* Kullanıcı sisteme giriş yaptı mı ? *@
                        {
                            <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="SignUp">Kayıt Ol</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="SignIn">Giriş Yap</a></li>
                        }
                        else
                        {
                            <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="LogOut">Çıkış Yap</a></li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()

    <!-- Footer-->
    <footer class="py-4 bg-black fixed-bottom">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2021</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/themes/js/scripts.js"></script>

    @RenderSection("script", false)

</body>
</html>